### PR TITLE
Update hello.txt

### PR DESCRIPTION
**Pull request by zhaotao513**
this code is too lower for you

### CODE REVIEW

**Comment by zhaotao916** [comment]
what you say ?ha?

**Comment by zhaotao513** [comment]
i say you are loser

**Comment by zhaotao916** [comment]
aaaaaaaaa

**Comment by zhaotao513** [comment]
i love zhangmin

**Comment by zhaotao916** [comment]
i love zhangmin too

**Comment by zhaotao916** [comment]
i love  zhangmin toooooooooooooo

**Comment by zhaotao513** [comment]
so do I

**Comment by zhaotao916** [comment]
haahhah

**Comment by zhaotao513** [comment]
hahhahahha

**Pull request merged**
